[versions]
# libraries
caffeine = "3.1.8"
commons-compress = "1.21"
commons-io = "2.16.1"
trustify-da-api-spec = "2.0.2"
trustify-da-java-client = "0.0.11"
github-api = "1.314"
junit = "4.13.2"
mockito = "4.11.0"
packageurl-java = "1.4.1"

# plugins
gradleIntelliJPlugin = "2.6.0"

[libraries]
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commons-compress" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
trustify-da-api-spec = { group = "io.github.guacsec", name = "trustify-da-api-model", version.ref = "trustify-da-api-spec" }
trustify-da-java-client = { group = "io.github.guacsec", name = "trustify-da-java-client", version.ref = "trustify-da-java-client" }
github-api = { group = "org.kohsuke", name = "github-api", version.ref = "github-api" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
packageurl-java = { group = "com.github.package-url", name = "packageurl-java", version.ref = "packageurl-java" }

[plugins]
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }


